version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./db-data-local/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zeus_app
      POSTGRES_HOST: db
      POSTGRES_EXTERNAL_PORT: 5432

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
