default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: s3_courses_learning_development

test:
  <<: *default
  database: s3_courses_learning_test

production:
  <<: *default
  database: s3_courses_learning_production
  username: s3_courses_learning
  password: <%= ENV['S3_COURSES_LEARNING'] %>
