default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zeus_app
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: s3_courses_learning_test

production:
  <<: *default
  database: s3_courses_learning_production
  username: s3_courses_learning
  password: <%= ENV['S3_COURSES_LEARNING'] %>
